name: Fetch Google Scholar Citations
on:
  schedule:
    - cron: '0 15 * * *' # Runs daily at 15:00 UTC
  workflow_dispatch: # Allows manual triggering
jobs:
  fetch-citations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Dependencies
        run: npm install axios
      
      - name: Fetch Google Scholar Citations
        env:
          GOOGLE_SCHOLAR_API_URL: ${{ secrets.GOOGLE_SCHOLAR_API_URL }}
          GOOGLE_SCHOLAR_API_KEY: ${{ secrets.GOOGLE_SCHOLAR_API_KEY }}
        run: |
          cat > fetch-citations.js << EOL
          const axios = require('axios');
          const fs = require('fs');
          
          async function fetchCitations() {
            try {
              const response = await axios.get(process.env.GOOGLE_SCHOLAR_API_URL, {
                headers: { 
                  'Authorization': \`Bearer \${process.env.GOOGLE_SCHOLAR_API_KEY}\`
                }
              });
              const data = response.data;
              fs.writeFileSync('citations.json', JSON.stringify(data, null, 2));
              console.log('Citations fetched and saved to citations.json');
            } catch (error) {
              console.error('Error fetching citations:', error);
              process.exit(1);
            }
          }
          
          fetchCitations();
          EOL
          
          node fetch-citations.js
      
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add citations.json
          git commit -m "Update citations [skip ci]" || echo "No changes to commit"
          git push
